weather:
  api:
    key: "cf002751564a4c78f5f7ed479f1b9ba3"

feign:
  client:
    config:
      httpBinClient:
        read-timeout: 2000
        connect-timeout: 1000
  circuitbreaker:
    enabled: true